version: “3.1”
services:
  mongo:
    image: postgres
    container_name: helloPostgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432